package com.example.aiinterview.domain.entity

// ──────────────────────────────────────────────────────────────────────────────
// Pure domain models — zero Android / framework dependencies
// ──────────────────────────────────────────────────────────────────────────────

/** A question generated by Claude for one practice round. */
data class InterviewQuestion(
    val text  : String,
    val topic : String
)

/** Claude's structured evaluation of the candidate's answer. */
data class ScoreResult(
    val score        : Int,           // 1–10
    val label        : String,        // Outstanding | Strong | Developing | Weak
    val strengths    : List<String>,
    val improvements : List<String>,
    val summary      : String
) {
    val tier: ScoreTier get() = when {
        score >= 9 -> ScoreTier.OUTSTANDING
        score >= 7 -> ScoreTier.STRONG
        score >= 5 -> ScoreTier.DEVELOPING
        else       -> ScoreTier.WEAK
    }
}

enum class ScoreTier { OUTSTANDING, STRONG, DEVELOPING, WEAK }

/** A completed practice session persisted in Room. */
data class ChatSession(
    val id        : Long,
    val createdAt : Long,
    val topic     : String,
    val question  : String,
    val answer    : String,
    val score     : Int,
    val label     : String,
    val summary   : String
)
